<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>e9bc7954-2bdd-4463-acf6-2ab4c38b3777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-litms-control-urn='login-submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-litms-control-urn='login-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-litms-control-urn='login-submit']</value>
      <webElementGuid>d887b2cb-b7ba-4aa5-892c-48e8b0f9a241</webElementGuid>
   </webElementProperties>
</WebElementEntity>
